### ISSUE TITLE
Step by step Guide To setting up Git + Git Desktop

### ISSUE THREAD

**Issue by Unwoolywookie** [szabgab/awesome-for-non-programmers#18]
I'm very new at coding but would like to learn more using Git and completing some simple tasks but I can't find Simple Easy to understand Instructions anywhere. would be nice to have the full code written out ready if that's possible? I can't learn you see if I can't install it. Hope it was ok for me to write this comment :) thanks you brainy skilful set of Coders. Amazing tech we all have is all thanks to you guys 👍

**Comment by tenhobi** [comment]
You can try stuff on https://try.github.io/ and https://learngitbranching.js.org/. I think it's pretty simple to understand. :-)

**Comment by szabgab** [comment]
I've written a book to help people contribute via GitHub: https://leanpub.com/collab-dev-git
