### ISSUE TITLE
Nominate Apache Answer for Non-programmers 

### ISSUE THREAD

**Issue by PrimmaAnna** [szabgab/awesome-for-non-programmers#86]
Apache Answer is an open source project built by passionate users, contributors, and PMC members. We are committed to creating an open and inclusive community, and we welcome everyone to join us in embracing the Apache way and building open source together.

Anyone can contribute to Answer. In addition to contributing code, there are many other ways to get involved, such as, use and test Answer, improve our docs, translation, share us on social media, etc. 

We've got a complete what-and-how contribution doc here: https://answer.apache.org/community/contributing

**Comment by szabgab** [comment]
Thanks, but this list should contain items that are aimed at non-programmers and what you described would be true for every application.
