### ISSUE TITLE
Suggestion: Removing Projects That No Longer Accept Contributions

### ISSUE THREAD

**Issue by derMattie** [szabgab/awesome-for-non-programmers#90]
Hello everyone
First, thank you for maintaining this list for contributors!

I noticed that the project [Liar Game](https://github.com/amphinomid/liar) in the list no longer accepts contributions. Which is stated here [Update: Life has gotten busy...](https://github.com/amphinomid/liar?tab=readme-ov-file#update-life-has-gotten-busy-and-i-no-longer-have-the-bandwidth-to-maintain-this-project-so-its-no-longer-accepting-contributions-and-the-web-app-is-no-longer-up-thanks-to-everyone-who-contributed-while-it-was-active-and-feel-free-to-fork-it-and-make-it-your-own--thanks-also-to-everyone-who-played-the-more-than-10k-games--i-hope-it-was-a-source-of-fun)
Since this list is specifically for projects welcoming contributions, I believe it might be worth considering its removal to avoid confusion for potential contributors.

Would it make sense to review and potentially remove projects that are no longer active or accepting contributions? Alternatively, a new section could be added for archived or inactive projects.

Looking forward to your thoughts!

Thank you, derMatt

**Comment by szabgab** [comment]
The new section sounds better. Thanks for the suggestion and for the PR.
